# fly.toml app configuration file generated for trailassociation-uk on 2026-06-08T15:49:28+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'trailassociation-uk'
primary_region = 'lhr'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
  processes = ['app']
